<?php 
<table>
<thead>
    <tr>
        <th>Marca</th>
        <th>Modelo</th>
        <th>Cilindraje</th>
        <th>Nombe</th>
    </tr>
</thead>
<tbody>
    {foreach $motos as $moto}
    <tr>
        <td>{$moto->marca}</td>
        <td>{$moto->modelo}</td>
        <td>{$moto->cilindraje}</td>
        <td>{$moto->nombre}</td>
    </tr>
    {/foreach}
</tbody>
</table>
    phpinfo(); 
